In [2]:
import numpy
# from tabulate import tabulate
class SubSetSum:
    def __init__(self,inputArray,suM):
        self.inputArray = inputArray
        self.suM = suM
        self.dpArray = numpy.full((len(self.inputArray)+1,self.suM+1),False)
        
    def defUPdateDpArray(self):
        #Update first Row with True
        for i in range(len(self.inputArray)+1):
            self.dpArray[i][0] = True
        for i in range(1,len(self.inputArray)+1):
            for j in range(1,self.suM+1):
                #Just to copy the previous generated value till we don't reach the row value
                #A way of memoization
                if j < self.inputArray[i-1]:
                    #This case if to manage index error in array
                    self.dpArray[i][j] = self.dpArray[i-1][j]
                else:
                    #Just to copy the previous generated value till we don't reach the row value
                    #A way of memoization
                    if self.dpArray[i-1][j]:
                        self.dpArray[i][j] = self.dpArray[i-1][j]
                    #Putting the value with the help of formula
                    else:
                        self.dpArray[i][j] = self.dpArray[i-1][j-self.inputArray[i-1]]
    def getSingleSubSet(self):
        resultList = []
        if self.dpArray[len(self.inputArray)][self.suM]:
            print("----- Found the result -----")
            i = len(self.inputArray)
            j = self.suM
            print(self.dpArray)
            while(i > 0 and j > 0):
                if not self.dpArray[i-1][j]:
                    resultList.append(self.inputArray[i-1])
                    #Updating the value for j
                    j = self.suM = self.suM-self.inputArray[i-1]
                    i-=1
                else:
                    i-=1
        else:
            print("No Its Not possible")
        return resultList
                    
    def getSubsetSum(self):
        self.defUPdateDpArray()
        return(self.getSingleSubSet())

input1 = [1,3,4,5,7,9]
suMM = 9
subSet = SubSetSum(input1,suMM)
print(subSet.getSubsetSum())

----- Found the result -----
[[ True False False False False False False False False False]
 [ True  True False False False False False False False False]
 [ True  True False  True  True False False False False False]
 [ True  True False  True  True  True False  True  True False]
 [ True  True False  True  True  True  True  True  True  True]
 [ True  True False  True  True  True  True  True  True  True]
 [ True  True False  True  True  True  True  True  True  True]]
[5, 3, 1]


In [1]:
import numpy
# from tabulate import tabulate
class SubSetSum:
    def __init__(self,inputArray,suM):
        self.inputArray = inputArray
        self.suM = suM
        self.dpArray = numpy.full((len(self.inputArray)+1,self.suM+1),0)
    def defUPdateDpArray(self):
        #Update first Row with 1
        for i in range(len(self.inputArray)+1):
            self.dpArray[i][0] = 1
        for i in range(1,len(self.inputArray)+1):
            for j in range(1,self.suM+1):
                if j < self.inputArray[i-1]:
                    self.dpArray[i][j] = self.dpArray[i-1][j]
                else:
                    self.dpArray[i][j] = self.dpArray[i-1][j-self.inputArray[i-1]] + self.dpArray[i-1][j]
    def getSingleSubSet(self):
        resultList = []
        if self.dpArray[len(self.inputArray)][self.suM]:
            print("----- Found the result -----")
            print("Total Subset which get formed are these %s" % (self.dpArray[len(self.inputArray)][self.suM]))
        else:
            print("No Its Not possible")
                    
    def getSubsetSum(self):
        self.defUPdateDpArray()
        print(self.dpArray)
        return(self.getSingleSubSet())

input1 = [1,3,4,5,7,9]
suMM = 9
subSet = SubSetSum(input1,suMM)
subSet.getSubsetSum()

[[1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 0 1 1 0 0 0 0 0]
 [1 1 0 1 2 1 0 1 1 0]
 [1 1 0 1 2 2 1 1 2 2]
 [1 1 0 1 2 2 1 2 3 2]
 [1 1 0 1 2 2 1 2 3 3]]
----- Found the result -----
Total Subset which get formed are these 3


In [2]:
class Node:
    def __init__(self,data):
        self.data = data
        self.next = None
class Stack:
    def __init__(self, Node, max_items):
        self.head = None
        self.Node = Node
        self.max_items = max_items
        self.len = 0
        if not "next" in dir(Node('_')):
            raise Exception('Node Class must have next variable')

    def push(self, node):
        if self.head is None:
            self.head = self.Node(node)
            self.len += 1
        elif self.len < self.max_items:
            current = self.head
            self.head = self.Node(node)
            self.head.next = current
            self.len += 1
        else:
            raise Exception("Stack Memory is Full")

    def pop(self):
        if self.len == 0:
            raise Exception("Stack Is empty")
        else:
            self.len -= 1
            deleted_node = self.head
            self.head = self.head.next
            return deleted_node

    def print_stack(self):
        current = self.head
        if self.len:
            while current.next is not None:
                print(current.data)
                current = current.next
            print(current.data)
        else:
            print('Stack is empty')

    def __len__(self):
        return self.len


stack = Stack(Node, 6)
for x in range(1, 7):
    try:
        stack.print_stack()
        stack.push(x)
        print()
    except Exception as e:
        print(e)
        break
stack.print_stack()
print()
stack.pop()

Stack is empty

1

2
1

3
2
1

4
3
2
1

5
4
3
2
1

6
5
4
3
2
1



In [23]:
import numpy
# from tabulate import tabulate
class SubSetSum:
    def __init__(self,inputArray,suM):
        self.inputArray = inputArray
        self.suM = suM
        self.dpArray = numpy.full((len(self.inputArray)+1,self.suM+1),False)
        
    def defUPdateDpArray(self):
        #Update first Row with True
        for i in range(len(self.inputArray)+1):
            self.dpArray[i][0] = True
        for i in range(1,len(self.inputArray)+1):
            for j in range(1,self.suM+1):
                #Just to copy the previous generated value till we don't reach the row value
                #A way of memoization
                if j < self.inputArray[i-1]:
                    #This case if to manage index error in array
                    self.dpArray[i][j] = self.dpArray[i-1][j]
                else:
                    #Just to copy the previous generated value till we don't reach the row value
                    #A way of memoization
                    if self.dpArray[i-1][j]:
                        self.dpArray[i][j] = self.dpArray[i-1][j]
                    #Putting the value with the help of formula
                    else:
                        self.dpArray[i][j] = self.dpArray[i-1][j-self.inputArray[i-1]]
    def getSingleSubSet(self):
        resultList = []
        if self.dpArray[len(self.inputArray)][self.suM]:
            print("----- Found the result -----")
            i = len(self.inputArray)
            j = self.suM
            print(self.dpArray)
            if self.inputArray[i-1] == self.suM:
                resultList.append([9])
            while(i > 0 and j > 0):
                if self.dpArray[i-1][j]:
                    if self.dpArray[j-self.dpArray[i-1]]:
                        resultList
                    i-=1
                    j-=1
                    #check the list and work 
                else:
                    #just move the i cursor on the top
                    i-=1
        else:
            print("No Its Not possible")
        return resultList
                    
    def getSubsetSum(self):
        self.defUPdateDpArray()
        return(self.getSingleSubSet())

input1 = [1,3,4,9,5,7]
suMM = 9
subSet = SubSetSum(input1,suMM)
print(subSet.getSubsetSum())

----- Found the result -----
[[ True False False False False False False False False False]
 [ True  True False False False False False False False False]
 [ True  True False  True  True False False False False False]
 [ True  True False  True  True  True False  True  True False]
 [ True  True False  True  True  True False  True  True  True]
 [ True  True False  True  True  True  True  True  True  True]
 [ True  True False  True  True  True  True  True  True  True]]


IndexError: index 8 is out of bounds for axis 0 with size 7

In [51]:
class Node:
    def __init__(self,data):
        self.data = data
        self.next = None
        if not "next" in dir(Node(_)):
            raise Exception('Node Class must have next variable')
            
print(help(Node(_)))

RecursionError: maximum recursion depth exceeded

In [3]:
class Node:
    def __init__(self,*args,**kwrgs):
        for arg in args:
            self.__dict__[arg]=None
        for krg in kwrgs:
            self.__dict__[krg] = kwrgs[krg]
        print(self)
print(Node('next',data= 10))